{{- if .Values.mcpServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-mcp-server-svc
  labels:
    {{- include "todo-app.mcpServer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mcpServer.service.type }}
  ports:
    - port: {{ .Values.mcpServer.service.port }}
      targetPort: {{ .Values.mcpServer.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "todo-app.mcpServer.selectorLabels" . | nindent 4 }}
{{- end }}
